// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "a6fad397-ea75-45d2-8dc3-c94605d6ed7b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1565719771);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1565719936);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1565719245);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1565719531);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1565719379);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1565719651);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 39791);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3ad31afd-d0bd-4c93-b9fd-021f225d70f2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1565719264830");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1565721058830");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1565719108314");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1565722708314");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190719090350");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1565719908");
user_pref("browser.startup.homepage_override.buildID", "20190719090350");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1565719907);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Startpage");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "fcb21e6402c7414bbe49e41df5321314");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 09 Aug 2019 09:59:13 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1565719772);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190719090350");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{d46ebbf8-cec4-4107-bd43-ab25b75bb6bb}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"fb4d276b-01b9-42cb-9e70-1fa9cef712a3\",\"fxmonitor@mozilla.org\":\"5f2cb424-2a16-4889-adf7-84034d85b403\",\"screenshots@mozilla.org\":\"ff18c5c1-b5d7-4f8f-9821-a5a04eebe6ff\",\"webcompat-reporter@mozilla.org\":\"ba915271-3412-47fa-af3d-f5af2a32ddc8\",\"webcompat@mozilla.org\":\"02130c6c-5443-4ebc-889f-4ec3d19e2984\",\"default-theme@mozilla.org\":\"c5e36646-8dbc-4b86-ac4c-1e965f87ab64\",\"yahoo@search.mozilla.org\":\"c2ce6afc-a603-4ac0-a88a-2144f031ac52\",\"startpage@search.mozilla.org\":\"58189b30-f5ce-4ca2-84e8-82874c3df961\",\"duckduckgo@search.mozilla.org\":\"be0cbddc-ed80-4ffc-a5f6-6cc671694d51\",\"twitter@search.mozilla.org\":\"34d9639b-cc54-4e47-9e50-d36eaa0dcd59\",\"wikipedia@search.mozilla.org\":\"195eefa5-a4e8-4c48-8940-c92e03d1158f\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1565719773);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b7f8d133-5ab4-41e8-890d-b2cc7f894678");
user_pref("security.sandbox.plugin.tempDirSuffix", "107dc511-34be-43e8-b165-be38c8684fc1");
user_pref("services.blocklist.pinning.checked", 1565719941);
user_pref("services.settings.clock_skew_seconds", -290);
user_pref("services.settings.last_etag", "\"1565717716453\"");
user_pref("services.settings.last_update_seconds", 1565719941);
user_pref("services.settings.main.cfr-fxa.last_check", 1565719941);
user_pref("services.settings.main.cfr.last_check", 1565719941);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1565719941);
user_pref("services.settings.main.hijack-blocklists.last_check", 1565719941);
user_pref("services.settings.main.language-dictionaries.last_check", 1565719941);
user_pref("services.settings.main.normandy-recipes.last_check", 1565719941);
user_pref("services.settings.main.onboarding.last_check", 1565719941);
user_pref("services.settings.main.sites-classification.last_check", 1565719941);
user_pref("services.settings.main.tippytop.last_check", 1565719941);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1565719941);
user_pref("services.settings.security.onecrl.checked", 1565719941);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1565719905);
user_pref("toolkit.telemetry.cachedClientID", "60e7f98a-dc77-4a9d-b5d8-b1ca5a577173");
user_pref("toolkit.telemetry.previousBuildID", "20190719090350");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
